# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id_suporte', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('encerrado', 'Encerrado')], default='aberto', max_length=14, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Chamado de Suporte',
                'verbose_name_plural': 'Chamados de Suporte',
                'db_table': 'suporte',
                'managed': True,
            },
        ),
    ]
