-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 17:42:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hub_fecc_of
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hub_fecc_of
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hub_fecc_of` DEFAULT CHARACTER SET utf8mb4 ;
USE `hub_fecc_of` ;

-- -----------------------------------------------------
-- Table `hub_fecc_of`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf_cnpj` VARCHAR(18) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `whatsapp` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_perfil` ENUM('fornecedor', 'comerciante') NOT NULL,
  `status_conta` ENUM('ativa', 'suspensa') NULL DEFAULT 'ativa',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_cnpj` (`cpf_cnpj` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`plano_assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`plano_assinatura` (
  `id_plano` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_plano` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`assinatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`assinatura` (
  `id_assinatura` INT(11) NOT NULL AUTO_INCREMENT,
  `id_fornecedor` INT(11) NOT NULL,
  `id_plano` INT(11) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `status` ENUM('ativa', 'suspensa', 'cancelada', 'expirada') NULL DEFAULT 'ativa',
  PRIMARY KEY (`id_assinatura`),
  INDEX `id_fornecedor` (`id_fornecedor` ASC) VISIBLE,
  INDEX `id_plano` (`id_plano` ASC) VISIBLE,
  CONSTRAINT `assinatura_ibfk_1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `assinatura_ibfk_2`
    FOREIGN KEY (`id_plano`)
    REFERENCES `hub_fecc_of`.`plano_assinatura` (`id_plano`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`avaliacao` (
  `id_comerciante` INT(11) NOT NULL,
  `id_fornecedor` INT(11) NOT NULL,
  `nota` TINYINT(4) NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `data_avaliacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `status_moderacao` ENUM('ativa', 'removida') NULL DEFAULT 'ativa',
  PRIMARY KEY (`id_comerciante`, `id_fornecedor`),
  INDEX `id_fornecedor` (`id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `avaliacao_ibfk_1`
    FOREIGN KEY (`id_comerciante`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `avaliacao_ibfk_2`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`categoria_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`categoria_insumo` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `status` ENUM('ativa', 'inativa') NULL DEFAULT 'ativa',
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`demanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`demanda` (
  `id_demanda` INT(11) NOT NULL AUTO_INCREMENT,
  `id_comerciante` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `descricao_produto` TEXT NOT NULL,
  `quantidade_produto` VARCHAR(100) NOT NULL,
  `data_publicacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `status` ENUM('publicada', 'encerrada') NULL DEFAULT 'publicada',
  PRIMARY KEY (`id_demanda`),
  INDEX `id_comerciante` (`id_comerciante` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `demanda_ibfk_1`
    FOREIGN KEY (`id_comerciante`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `demanda_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `hub_fecc_of`.`categoria_insumo` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`produto` (
  `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_fornecedor` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `telefone_contato` VARCHAR(20) NULL DEFAULT NULL,
  `whatsapp_contato` VARCHAR(20) NULL DEFAULT NULL,
  `status` ENUM('ativo', 'inativo') NULL DEFAULT 'ativo',
  `data_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_produto`),
  INDEX `id_fornecedor` (`id_fornecedor` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `produto_ibfk_1`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `produto_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `hub_fecc_of`.`categoria_insumo` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`denuncia` (
  `id_denuncia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_denunciante` INT(11) NOT NULL,
  `tipo_conteudo` ENUM('portfolio', 'demanda') NOT NULL,
  `id_produto` INT(11) NULL DEFAULT NULL,
  `id_demanda` INT(11) NULL DEFAULT NULL,
  `descricao` TEXT NOT NULL,
  `evidencia` VARCHAR(500) NULL DEFAULT NULL,
  `status` ENUM('pendente', 'arquivada', 'procedente') NULL DEFAULT 'pendente',
  `data_denuncia` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_denuncia`),
  INDEX `id_denunciante` (`id_denunciante` ASC) VISIBLE,
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  INDEX `id_demanda` (`id_demanda` ASC) VISIBLE,
  CONSTRAINT `denuncia_ibfk_1`
    FOREIGN KEY (`id_denunciante`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `denuncia_ibfk_2`
    FOREIGN KEY (`id_produto`)
    REFERENCES `hub_fecc_of`.`produto` (`id_produto`),
  CONSTRAINT `denuncia_ibfk_3`
    FOREIGN KEY (`id_demanda`)
    REFERENCES `hub_fecc_of`.`demanda` (`id_demanda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`favorito` (
  `id_comerciante` INT(11) NOT NULL,
  `id_fornecedor` INT(11) NOT NULL,
  `data_favoritado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_comerciante`, `id_fornecedor`),
  INDEX `id_fornecedor` (`id_fornecedor` ASC) VISIBLE,
  CONSTRAINT `favorito_ibfk_1`
    FOREIGN KEY (`id_comerciante`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `favorito_ibfk_2`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`log_alteracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`log_alteracao` (
  `id_log` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `acao` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `modelo_afetado` VARCHAR(50) NOT NULL,
  `id_registro_afetado` INT(11) NOT NULL,
  `conteudo_anterior` TEXT NULL DEFAULT NULL,
  `data_alteracao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_log`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `log_alteracao_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`suporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`suporte` (
  `id_suporte` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `assunto` VARCHAR(200) NOT NULL,
  `descricao` TEXT NOT NULL,
  `img` VARCHAR(500) NULL DEFAULT NULL,
  `status` ENUM('aberto', 'em_atendimento', 'encerrado') NULL DEFAULT 'aberto',
  `data_abertura` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_suporte`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `suporte_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`termo_uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`termo_uso` (
  `id_termo_uso` INT(11) NOT NULL AUTO_INCREMENT,
  `versao` VARCHAR(20) NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `data_vigencia` DATE NOT NULL,
  PRIMARY KEY (`id_termo_uso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hub_fecc_of`.`termo_aceite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hub_fecc_of`.`termo_aceite` (
  `id_aceite` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_termo_uso` INT(11) NOT NULL,
  `data_aceite` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_aceite`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_termo_uso` (`id_termo_uso` ASC) VISIBLE,
  CONSTRAINT `termo_aceite_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `hub_fecc_of`.`usuario` (`id_usuario`),
  CONSTRAINT `termo_aceite_ibfk_2`
    FOREIGN KEY (`id_termo_uso`)
    REFERENCES `hub_fecc_of`.`termo_uso` (`id_termo_uso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
