# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Insumo',
                'verbose_name_plural': 'Categorias de Insumo',
                'db_table': 'categoria_insumo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TermoUso',
            fields=[
                ('id_termo_uso', models.AutoField(primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('data_vigencia', models.DateField()),
            ],
            options={
                'verbose_name': 'Termo de Uso',
                'verbose_name_plural': 'Termos de Uso',
                'db_table': 'termo_uso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('INSERT', 'Inserção'), ('UPDATE', 'Atualização'), ('DELETE', 'Remoção')], max_length=6)),
                ('modelo_afetado', models.CharField(max_length=50)),
                ('id_registro_afetado', models.IntegerField()),
                ('conteudo_anterior', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alteração',
                'db_table': 'log_alteracao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TermoAceite',
            fields=[
                ('id_aceite', models.AutoField(primary_key=True, serialize=False)),
                ('data_aceite', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='usuarios.usuario')),
                ('id_termo_uso', models.ForeignKey(db_column='id_termo_uso', on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='core.termouso')),
            ],
            options={
                'verbose_name': 'Aceite de Termo',
                'verbose_name_plural': 'Aceites de Termo',
                'db_table': 'termo_aceite',
                'managed': True,
            },
        ),
    ]
