# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('pk', models.CompositePrimaryKey('id_comerciante', 'id_fornecedor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('status_moderacao', models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('removida', 'Removida')], default='ativa', max_length=8, null=True)),
                ('id_comerciante', models.ForeignKey(db_column='id_comerciante', limit_choices_to={'tipo_perfil': 'comerciante'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='usuarios.usuario')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', limit_choices_to={'tipo_perfil': 'fornecedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('pk', models.CompositePrimaryKey('id_comerciante', 'id_fornecedor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('data_favoritado', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_comerciante', models.ForeignKey(db_column='id_comerciante', limit_choices_to={'tipo_perfil': 'comerciante'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.usuario')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', limit_choices_to={'tipo_perfil': 'fornecedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorito',
                'managed': True,
            },
        ),
    ]
