# Generated by Django 6.1.1 on 2026-09-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_perfil', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('comerciante', 'Comerciante')], max_length=11)),
                ('status_conta', models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa')], default='ativa', max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
