# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('nome_plano', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'db_table': 'plano_assinatura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id_assinatura', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='ativa', max_length=9, null=True)),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', limit_choices_to={'tipo_perfil': 'fornecedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='usuarios.usuario')),
                ('id_plano', models.ForeignKey(db_column='id_plano', on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='assinaturas.planoassinatura')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'assinatura',
                'managed': True,
            },
        ),
    ]
