# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_conteudo', models.CharField(choices=[('portfolio', 'Portfólio'), ('demanda', 'Demanda')], max_length=9)),
                ('descricao', models.TextField()),
                ('evidencia', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('arquivada', 'Arquivada'), ('procedente', 'Procedente')], default='pendente', max_length=10, null=True)),
                ('data_denuncia', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_demanda', models.ForeignKey(blank=True, db_column='id_demanda', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='demandas.demanda')),
                ('id_denunciante', models.ForeignKey(db_column='id_denunciante', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to='usuarios.usuario')),
                ('id_produto', models.ForeignKey(blank=True, db_column='id_produto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='portfolio.produto')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'db_table': 'denuncia',
                'managed': True,
            },
        ),
    ]
