# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=7, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoriainsumo')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', limit_choices_to={'tipo_perfil': 'fornecedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos (Portfólio)',
                'db_table': 'produto',
                'managed': True,
            },
        ),
    ]
