# Generated by Django 6.1.1 on 2026-09-07 22:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id_demanda', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_produto', models.TextField()),
                ('quantidade_produto', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('publicada', 'Publicada'), ('encerrada', 'Encerrada')], default='publicada', max_length=9, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to='core.categoriainsumo')),
                ('id_comerciante', models.ForeignKey(db_column='id_comerciante', limit_choices_to={'tipo_perfil': 'comerciante'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'db_table': 'demanda',
                'managed': True,
            },
        ),
    ]
